### ISSUE TITLE
Smithy barfs on bad commands

### ISSUE THREAD

**Issue by robertdfrench** [AnthonyDiGirolamo/smithy#3]
```
[frenchrd@sith-login1 ~]$ smithy list
==> ERROR: Unknown command 'list'
/sw/tools/smithy/gems/software_smithy-1.6.3/bin/smithy:698:in `block in <top (required)>': uninitialized class variable @@global_config in Object (NameError)
        from /sw/tools/smithy/gems/gli-2.7.0/lib/gli/app_support.rb:261:in `call'
        from /sw/tools/smithy/gems/gli-2.7.0/lib/gli/app_support.rb:261:in `regular_error_handling?'
        from /sw/tools/smithy/gems/gli-2.7.0/lib/gli/app_support.rb:207:in `handle_exception'
        from /sw/tools/smithy/gems/gli-2.7.0/lib/gli/app_support.rb:88:in `rescue in run'
        from /sw/tools/smithy/gems/gli-2.7.0/lib/gli/app_support.rb:61:in `run'
        from /sw/tools/smithy/gems/software_smithy-1.6.3/bin/smithy:704:in `<top (required)>'
        from /sw/tools/smithy/bin/smithy:23:in `load'
        from /sw/tools/smithy/bin/smithy:23:in `<main>'
```

**Comment by AnthonyDiGirolamo** [comment]
This should be fixed
